### ISSUE TITLE
xseei.import.js error 

### ISSUE THREAD

**Issue by go2tom42** [nohamelin/xseei#5]
Using xml files exported with xseei.export-all.js

error on all is 50 XML files are similar to this with just the file name that differs 
`Import of a search engine from the file 'docker-hub.xml' failed: Could not convert JavaScript argument arg 3 [nsIBrowserSearchService.addEngine]`

**Comment by nohamelin** [comment]
Thanks for the report, I will investigate it.

**Comment by redactedscribe** [comment]
Same error when trying to run `xseei.import.js`. Any news on a fix?

**Comment by macko-125** [comment]
The error is caused because the obsolete dataType parameter for nsIBrowserSearchService.addEngine was removed since Firefox 64. See also here ► [Bug 1481199](https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1481199)

To fix the issue in the xseei.import.js script, one has to simply remove line/row 158 of the script (`Ci.nsISearchEngine.DATA_XML,`), to get the import working again.

**Comment by nohamelin** [comment]
Thanks for the bug number, I will fix it as soon as possible.

**Comment by nohamelin** [comment]
An update for the xseei.import.js script has been pushed; sorry for the long wait.
